server:
  port: 8087

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/notification?useSSL=false
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

kafka:
  bootstrap-servers: localhost:9092
  listener:
    ack-mode: manual_immediate  # 수동 ack 모드
  consumer:
    group-id: BackendNotification
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    enable-auto-commit: false
    auto-offset-reset: latest
    properties:
      spring.json.trusted.packages: "*"
      spring.json.use.type.headers: false
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      spring.json.add.type.headers: false

firebase:
  config: ${FIREBASE_CONFIG:}